#!/bin/sh
### BEGIN INIT INFO
# Provides:             zomboid-server
# Required-Start:       $local_fs $network
# Required-Stop:        $local_fs $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Description:          Project Zomboid Server
### END INIT INFO

###### Project Zomboid Server Service script ######

case "$1" in
start)
printf "Server starting!\n"
nohup /home/pzuser/bin/./pzServerRestart.sh&
;;
stop)
printf "Server shutting down!\n"
rcon -a 127.0.0.1:27015 -p <INSERT SERVER RCON PASSWORD HERE> "quit"
;;
restart)
printf "Server restarting...\n"
rcon -a 127.0.0.1:27015 -p <INSERT SERVER RCON PASSWORD HERE> "save"
rcon -a 127.0.0.1:27015 -p <INSERT SERVER RCON PASSWORD HERE> "quit"
nohup /home/pzuser/bin/./pzServerRestart.sh&

;;
save)
rcon -a 127.0.0.1:27015 -p <INSERT SERVER RCON PASSWORD HERE> "save"
;;
*)
echo "Usage: {start|stop|restart|save}" >&2
exit 1
;;
esac
exit 0